#!/bin/sh
declare -a cydia 
cydia=($CYDIA)

mv /System/Library/Frameworks/MediaToolbox.framework/RegionalSystemSoundsThatShareBehaviour.plist /System/Library/Frameworks/MediaToolbox.framework/RegionalSystemSoundsThatShareBehaviour.plist.old
mv /usr/git/fix/MediaToolbox.framework/RegionalSystemSoundsThatShareBehaviour.plist /System/Library/Frameworks/MediaToolbox.framework/RegionalSystemSoundsThatShareBehaviour.plist
rm -r /usr/git

killall CommCenter
echo "==================================="
echo "Fix Shutter Sound all iPhone iPad iPod"
echo "Build v1.0~beta1 by iGosu"
echo "Cai dat thanh cong, Hay khoi dong lai may"
echo "Copyright iGosu @2018"
echo "==================================="
if [[ ${CYDIA+@} ]]; then
	eval "echo 'finish:reboot' >&${cydia[0]}"
fi
exit 0
