#!/bin/sh
declare -a cydia 
cydia=($CYDIA) 
echo "Restore Region Features；"
echo "Restore Region Features；"
echo "Restore Region Features；"

mv /System/Library/Frameworks/MediaToolbox.framework/RegionalSystemSoundsThatShareBehaviour.plist.old /System/Library/Frameworks/MediaToolbox.framework/RegionalSystemSoundsThatShareBehaviour.plist

killall CommCenter
echo "==================================="
echo "Fix Shutter Sound all iPhone iPad iPod"
echo "Build v1.0~beta1 by iGosu"
echo "Go bo thanh cong, Hay khoi dong lai"
echo "Copyright iGosu @2018"
echo "==================================="
if [[ ${CYDIA+@} ]]; then
	eval "echo 'finish:reboot' >&${cydia[0]}"
fi
exit 0
