#!/bin/sh
declare -a cydia 
cydia=($CYDIA)

mv /System/Library/RegionFutures/RegionFeatures_ipad.txt /usr/git/backups/
mv /System/Library/RegionFutures/RegionFeatures_iphone.txt /usr/git/backups/
mv /System/Library/RegionFutures/RegionFeatures_ipod.txt /usr/git/backups/

mv /usr/git/iGosu/RegionFeatures_ipad.txt /System/Library/RegionFutures/
mv /usr/git/iGosu/RegionFeatures_iphone.txt /System/Library/RegionFutures/
mv /usr/git/iGosu/RegionFeatures_ipod.txt /System/Library/RegionFutures/


killall CommCenter
echo "==================================="
echo "Fix Shutter Sound all iPhong iPad iPod "
echo "Build v1.0 by iGosu"
echo "Cai dat thanh cong, khoi dong lai de hoan tat viec fix loi"
echo "Copyright iGosu @2018"
echo "==================================="
if [[ ${CYDIA+@} ]]; then
	eval "echo 'finish:reboot' >&${cydia[0]}"
fi
exit 0
