#!/bin/sh
declare -a cydia 
cydia=($CYDIA) 
echo "Restore Region Features；"
echo "Restore Region Features；"
echo "Restore Region Features；"

rm -r /System/Library/RegionFutures/RegionFeatures_ipad.txt
rm -r /System/Library/RegionFutures/RegionFeatures_iphone.txt
rm -r /System/Library/RegionFutures/RegionFeatures_ipod.txt

mv /usr/git/backups/* /System/Library/RegionFutures/
rm -r /usr/git

killall CommCenter
echo "==================================="
echo "Fix Shutter Sound all iPhong iPad iPod "
echo "Build v1.0 by iGosu"
echo "Go bo thanh cong, khoi dong lai de hoan tat viec Khoi phuc lai ban cu"
echo "Copyright iGosu @2018"
echo "==================================="
if [[ ${CYDIA+@} ]]; then
	eval "echo 'finish:reboot' >&${cydia[0]}"
fi
exit 0
