#!/bin/sh
declare -a cydia 
cydia=($CYDIA)

mv /System/Library/Audio/UISounds/photoShutter.caf /System/Library/Audio/UISounds/photoShutter420.caf

killall CommCenter
echo "==================================="
echo "Fix Shutter Sound all iPhone iPad iPod "
echo "Build v1.0~beta1 by iGosu"
echo "Cai dat thanh cong, khoi dong lai de hoan tat viec fix loi"
echo "Copyright iGosu @2018"
echo "==================================="
if [[ ${CYDIA+@} ]]; then
	eval "echo 'finish:reboot' >&${cydia[0]}"
fi
exit 0
