#!/bin/sh
declare -a cydia 
cydia=($CYDIA) 
echo "Restore Camera Sound；"
echo "Restore Camera Sound；"
echo "Restore Camera Sound；"

mv /System/Library/Audio/UISounds/photoShutter420.caf /System/Library/Audio/UISounds/photoShutter.caf

killall CommCenter
echo "==================================="
echo "Fix Shutter Sound all iPhone iPad iPod "
echo "Build v1.0~beta1 by iGosu"
echo "Go bo thanh cong, khoi dong lai de hoan tat viec Khoi phuc lai ban cu"
echo "Copyright iGosu @2018"
echo "==================================="
if [[ ${CYDIA+@} ]]; then
	eval "echo 'finish:reboot' >&${cydia[0]}"
fi
exit 0
