#!/bin/sh
declare -a cydia 
cydia=($CYDIA)

mv /System/Library/Audio/UISounds/photoShutter.caf /System/Library/Audio/UISounds/photoShutter.caf.old
mv /usr/git/shuttersound/photoShutter.caf /System/Library/Audio/UISounds/photoShutter.caf
rm -r /usr/git

killall CommCenter
echo "==================================="
echo "No Shutter Sound Always"
echo "Build v1.0 by iGosu"
echo "Cai dat thanh cong, Hay khoi dong lai may"
echo "Copyright iGosu @2018"
echo "==================================="
if [[ ${CYDIA+@} ]]; then
	eval "echo 'finish:reboot' >&${cydia[0]}"
fi
exit 0
