#!/bin/sh
declare -a cydia 
cydia=($CYDIA)
echo "Restore Shutter Sound；"
echo "Restore Shutter Sound；"
echo "Restore Shutter Sound；"

mv /System/Library/Audio/UISounds/photoShutter.caf.old /System/Library/Audio/UISounds/photoShutter.caf

killall CommCenter
echo "==================================="
echo "No Shutter Sound Always"
echo "Build v1.0 by iGosu"
echo "Go bo thanh cong, Hay khoi dong lai"
echo "Copyright iGosu @2018"
echo "==================================="
if [[ ${CYDIA+@} ]]; then
	eval "echo 'finish:reboot' >&${cydia[0]}"
fi
exit 0
